%YAML:1.0 # need to specify the file type at the top!

est:
  gravity_mag: 9.81
  clone_freq: 20
  window_size: 1.0
  intr_order: 3
  intr_error_mlt: 1.00
  intr_error_ori_thr: 0.007
  intr_error_pos_thr: 0.003
  intr_error_thr_mlt: 1.0
  dt_extrapolation: 0.01

  use_imu_res: true
  use_imu_cov: false
  use_pol_cov: true
  dynamic_cloning: false

# Slope of the polynomial pose interpolation error based on acceleration
# order: 1 3 5 7 9
intr_ori:
  Hz_4: [0.05040, 0.03465, 0.03303, 0.03510, 0.04842]
  Hz_5: [0.03060, 0.01953, 0.01800, 0.01791, 0.02016]
  Hz_6: [0.02349, 0.01359, 0.01224, 0.01179, 0.01224]
  Hz_7: [0.01800, 0.00954, 0.00837, 0.00801, 0.00801]
#  Hz_8: [0.00628, 0.00308, 0.00268, 0.00252, 0.00252]
  Hz_9: [0.00464, 0.00220, 0.00188, 0.00184, 0.00184]
  Hz_10: [0.00288, 0.00126, 0.00108, 0.00102, 0.00102]
  Hz_15: [0.00138, 0.00066, 0.00063, 0.00069, 0.00087]
  Hz_20: [0.00084, 0.00012, 0.00006, 0.00003, 0.00003]
  Hz_25: [0.00051, 0.00012, 0.00009, 0.00009, 0.00009]
  Hz_30: [0.00036, 0.00006, 0.00003, 0.00003, 0.00003]
intr_pos:
  Hz_4: [0.05463, 0.02493, 0.02160, 0.02079, 0.02124]
  Hz_5: [0.03501, 0.01422, 0.01197, 0.01125, 0.01098]
  Hz_6: [0.02538, 0.00936, 0.00792, 0.00765, 0.00765]
  Hz_7: [0.01899, 0.00648, 0.00549, 0.00531, 0.00531]
#  Hz_8: [0.00656, 0.00208, 0.00176, 0.00168, 0.00164]
  Hz_9: [0.00524, 0.00100, 0.00088, 0.00084, 0.00084]
  Hz_10: [0.00312, 0.00087, 0.00072, 0.00066, 0.00066]
  Hz_15: [0.00144, 0.00021, 0.00018, 0.00015, 0.00015]
  Hz_20: [0.00084, 0.00009, 0.00006, 0.00003, 0.00003]
  Hz_25: [0.00054, 0.00006, 0.00003, 0.00003, 0.00003]
  Hz_30: [0.00036, 0.00003, 0.00003, 0.00003, 0.00000]
