%YAML:1.0 # need to specify the file type at the top!

gps:
  enabled: true
  max_n: 1
  do_calib_ext: false
  do_calib_dt: false
  init_distance: 20.0
  init_closed_form: true
  init_cov_dt: 1e-3
  init_cov_ex: 1e-1
  init_cov_inflation: 2.0
  chi2_mult: 9999
  overwrite_noise: true
  noise: 3.0

gps0:
  timeoffset: 0.0
  pGinI: [-0.25, 0, 0]
  topic: "/gps/fix"
